theme = "blowfish"
baseURL = "https://heidelberg-paartherapie.de/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
summaryLength = 30
enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
