[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About Us"
  pageRef = "ueber-uns"
  weight = 20

[[main]]
  name = "Services"
  pageRef = "angebot"
  weight = 30

[[main]]
  name = "Programme 2026"
  pageRef = "programm-2026"
  weight = 40

[[main]]
  name = "Contact & Fees"
  pageRef = "kontakt"
  weight = 50

[[footer]]
  name = "Legal Notice"
  pageRef = "impressum"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  pageRef = "datenschutz"
  weight = 20
