[[main]]
  name = "Angebot"
  pageRef = "angebot"
  weight = 10

[[main]]
  name = "Über uns"
  pageRef = "ueber-uns"
  weight = 20

[[main]]
  name = "Programm 2026"
  pageRef = "programm-2026"
  weight = 30

[[main]]
  name = "Anfahrt"
  pageRef = "anfahrt"
  weight = 40

[[main]]
  name = "Kontakt & Honorar"
  pageRef = "kontakt"
  weight = 50

[[footer]]
  name = "Impressum"
  pageRef = "impressum"
  weight = 10

[[footer]]
  name = "Datenschutz"
  pageRef = "datenschutz"
  weight = 20
